language: go

go:
	- "1.11.x"

env:
	- GO_ENV=test

services:
	- postgresql

before_script:
	- psql -c 'create database webapp_test;' -U postgres
	- mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/bhoy-troy/webapp

install:
	- go get github.com/gobuffalo/buffalo/buffalo
	- go get github.com/golang/dep/cmd/dep
	- dep ensure

script: buffalo test
